Repository silverstripe/cwp-starter-theme, pull requests merged in 2019-07, with the labels that each got.

#148 FIX Remove redundant title attributes for blog tags
  templates/Includes/BlogEntryTags.ss
Labels: affects/v4, change/patch, type/bug

#143 FIX Remove redundant FilteredUpdates title attribute
  templates/Includes/FilteredUpdates.ss
Labels: affects/v4, change/patch

#141 FIX Add tabindex to focus the results notification message
  templates/Layout/Page_results.ss
Labels: affects/v4, change/patch

#149 FIX Remove redundant tags title
  templates/Includes/UpdateTags.ss
Labels: affects/v4, change/patch, impact/low, type/bug

#144 FIX Reduce default font size in legends to 1rem
  dist/css/editor.css
  dist/css/main.css
  src/scss/components/forms.scss
  src/scss/typography.scss
Labels: affects/v4, change/patch

#153 FIX Add accessible name to reflect the components function
  templates/Includes/LanguageSelector.ss
Labels: affects/v4, change/patch

#158 FIX Rename date range and tag keys
  templates/Includes/DateRange.ss
  templates/Includes/UpdateTags.ss
Labels: affects/v4, change/patch
